# -*- coding: utf-8 -*-
"""teste_LINEARSVC_64%ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuYW4Xuj8f94LcSZaxwpS3_yoLyhut_f
"""

import pandas as pd

dados = pd.read_csv("Testes_ML_classi.csv")
dados.head()

x = dados[["Sexo","Solitude","Fumou","Pais_Fumante","amigod_drogados","idade"]]
y = dados[["Ja_bebeu"]]

x.head()

y.head()

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

x = dados[["Sexo","Solitude","Fumou","Pais_Fumante","amigod_drogados","idade"]]
y = dados[["Ja_bebeu"]]

SEED = 5
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25, stratify = y)

print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)