# -*- coding: utf-8 -*-
"""svc_68.78.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QClP9Xyc8sGbXMYL4FEsH3ZAKBur-HK4
"""

import pandas as pd
dados = pd.read_csv("/content/Testes_ML_classi_RJESTADO.csv")
dados.head()

x = dados[["Sexo","trabalha","pos_estudos","saude","engravidou" ,"Solitude","Fumou","Pais_Fumante","amigod_drogados","idade"]]
y = dados[["Ja_bebeu"]]

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

SEED = 5
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.10, stratify = y)

print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = SVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)