# -*- coding: utf-8 -*-
"""teste_svm_MAXACURACIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZj8EhcoVhpdluDj3EnqEB_ayNPlchQJ
"""

import pandas as pd

dados = pd.read_csv("Testes_ML_classi.csv")
dados.head()

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

x = dados[["Sexo","Solitude","Fumou","Pais_Fumante","amigod_drogados","idade"]]
y = dados[["Ja_bebeu"]]

SEED = 5
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.21, stratify = y)

print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = SVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

# MAX 

i = 0.10 #test size 

vetor_test = []
acu =[] #acuracias 


while i<1: 

  SEED = 5
  np.random.seed(SEED)
  treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = i , stratify = y)
  modelo = SVC()
  modelo.fit(treino_x, treino_y)
  previsoes = modelo.predict(teste_x)
  acuracia = accuracy_score(teste_y, previsoes) * 100

  acu.append(acuracia)
  vetor_test.append(i)
  i = i + 0.01
  print(i)

acu

n_max = (max(acu)) # Melhor valor para acuracia entre um intervalo de test_size de 0.10 até 0.99
n_pos = acu.index(n_max) # Posição do melhor valor

print(max(acu)) # valor da maior acuracia
print(n_pos) # Posição da maior acuracia

vetor_test[11] # valor do test que maximiza a acuracia do SVM, TEST_SIZE = 0.21